GET http://localhost:3000/users
###


GET http://localhost:3000/users/5f8b10ff59fb5d07007daa98
###


POST http://localhost:3000/users
Content-Type: application/json

{
  "firstName": "Vitalik",
  "lastName": "Peterherin",
  "avatar": "https://source.unsplash.com/collection/1346951/1000x500?sig=1",
  "aboutMe": "YA V AHUY",
  "socials": {
    "facebook": "facebook.com",
    "twitter": ""
  },
  "categories": [
      {
          "name": "123",
          "slug": "12345"
      }
  ]
}
###


PUT http://localhost:3000/users/5f959e2ec0cb41427ccf7412
Content-Type: application/json

{
  "firstName": "Vitalik",
  "lastName": "Peterherin",
  "avatar": "https://source.unsplash.com/collection/1346951/1000x500?sig=1",
  "aboutMe": "YA V AHUY",
  "socials": {
    "facebook": "facebook.com",
    "twitter": "",
    "linkedIn": "linkedIn.com"
  }
}
###


DELETE http://localhost:3000/users/5f8b131359fb5d07007daa99
###